# Generated by Django 5.1 on 2024-09-02 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='fat',
            new_name='fats',
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='protein',
            new_name='proteins',
        ),
    ]
