# Generated by Django 5.1 on 2024-09-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_fat_fooditem_fats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
